spring:
  application:
    name: Coffee_pos
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/Coffee_pos
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
